### ISSUE TITLE
Navbar display 

### ISSUE THREAD

**Issue by UrbainSibel** [SimonRTC/legends-game#5]
**BUG:**
Navbar displaying skin is wrong

**SCREENSHOT:**
![image](https://user-images.githubusercontent.com/60613250/96269128-40ce3b80-0fca-11eb-98fd-a59d5270c1dc.png)

**Comment by SimonRTC** [comment]
Can you explain more about this issue?

**Comment by UrbainSibel** [comment]
The background image is not fully displayed !

**Comment by SimonRTC** [comment]
Ok thanks I will see this issue monday!
